### PROD
GET https://goxo.cc/
Content-Type: application/json

### PROD 2
POST https://goxo.cc/api/v1/
Content-Type: application/json

### LOC
POST http://localhost:8080/api/v1
Content-Type: application/json

### Metrics
GET https://goxo.cc/metrics

### Loki
POST http://localhost:3100/loki/api/v1/push
Content-Type: application/json

{
  "streams": [
    {
      "stream": {
        "label": "myapp",
        "app": "myapplication"
      },
      "values": [
      ]
    }
  ]
}
